// ESLint v9 flat-config (DIL-319). Replaces the missing legacy
// `.eslintrc.*` so `npm run lint` runs again. Stack:
//
// - eslint-plugin-vue (Vue 3 SFCs)
// - typescript-eslint (parser + recommended rules in one)
// - eslint-config-prettier (turns off rules that fight Prettier; we
//   format via `npm run format`, lint enforces correctness only)
// - globals (browser env)
//
// Scope: src/ only. Tests, build output, node_modules, and the
// generated openapi types are ignored.

import js from '@eslint/js'
import vue from 'eslint-plugin-vue'
import tseslint from 'typescript-eslint'
import prettier from 'eslint-config-prettier'
import globals from 'globals'

export default [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'src/types/api.d.ts', // generated by `just api-types`
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...vue.configs['flat/recommended'],

  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.vue'],
      },
    },
    rules: {
      // Vue's multi-word-component-name rule fires on top-level
      // views like `Inbox` which we name to match the route. Off.
      'vue/multi-word-component-names': 'off',
      // Allow `_unused` named variables — useful for destructuring
      // when only the rest matters.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Pre-existing `any` usage is widespread; demoting to warn
      // surfaces it without breaking CI. Track tightening as a
      // codebase-wide cleanup follow-up.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },

  prettier,
]
