ALTER TABLE clubs ADD COLUMN website_url TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN chairman_email TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN treasurer_email TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN secretary_email TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN harbor_master_email TEXT NOT NULL DEFAULT '';
