DROP TABLE IF EXISTS invoice_lines;
DROP TABLE IF EXISTS invoices;
ALTER TABLE clubs DROP COLUMN IF EXISTS org_number;
ALTER TABLE clubs DROP COLUMN IF EXISTS address;
ALTER TABLE clubs DROP COLUMN IF EXISTS bank_account;
